markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments
baseurl: "/kansai-ruby-community"
encoding: UTF-8
exclude:
  - README.md
  - vendor
name: "関西Rubyコミュニティ"
copyright: 2026, Ruby 関西
swatchtheme: simplex
